# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

# Before running, please refer to https://docs.datawiza.com/guides/cvat.html for setting up.
#
# To run:
# docker-compose -f docker-compose.yml -f docker-compose.header-auth.yml up -d
#
# To shutdown:
# docker-compose -f docker-compose.yml -f docker-compose.header-auth.yml down
version: '3.3'

services:
  datawiza_access_broker:
    image: registry.gitlab.com/datawiza/access-broker
    container_name: datawiza-access-broker
    ports:
      - "443:443"
    restart: always
    environment:
      # To obtain a valid provisioning key-secret pair, please
      # visit https://console.datawiza.com/
      # And follow the step-by-step instruction in
      # https://docs.datawiza.com/guides/cvat.html
      PROVISIONING_KEY: ${YOUR_PROVISIONING_KEY}
      PROVISIONING_SECRET: ${YOUR_PROVISIONING_SECRET}
    networks:
      - cvat

  cvat_server:
    environment:
      HEADER_AUTH_ENABLE: 'true'

  traefik:
    # With Datawiza Access Proxy in front serving as the entry point,
    # the port 8080 is removed for traefik since it should no longer be exposed to the public.
    # The port 443 of the Datawiza Access Proxy becomes the publicly facing port.
    # All traffic will go through the Access Proxy for authentication and then
    # get passed to the upstream app/service.
    ports:
      - 8090:8090
